apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo-db
    namespace: mango
    labels:
       app: mongo

spec:
    replicas: 2
    selector:
      matchLabels:
        app: mongo
    template:
      metadata:
        labels:
          app: mongo
      spec:
        containers:
        - name: mongo
          image: mongo
          ports:
          - containerPort: 80